# change the followings to match your Github username and repo name
baseurl: "/tailpages" # the name of your github repo
url: "https://barrypeavy.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Barry Peavy: Web Designer | UI/UX Designer | Front End Developer"
description: Resume and portfolio site for Barry Peavy

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Barry Peavy
author-bio: Web Designer | UI/UX Designer | Front End Developer  # change to false to hide
author-image: barrypeavy-memoji-02.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: 
- text: Skills
  permalink: skills
- text: Experience
  permalink: experience
- text: Education
  permalink: education
- text: Portfolio
  permalink: portfolio

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/barrypeavy/tailpages

# google analytics
# google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
